name: unit-tests
on:
  push:
    branches:
      - main
jobs:
  Backend-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install requirements
        run: |
          cd backend
          pip install -r requirements.txt
      # TODO: test go here.
      - name: Run
        run: |
          pytest
      # TODO: test end here.
          echo "🍏 This job's status is ${{ job.status }}."